### ISSUE TITLE
Don't run osm2pgsql as database superuser

### ISSUE THREAD

**Issue by joto** [Xetnus/osm-finder#1]
I see this in your README:

```
sudo -u postgres osm2pgsql -d osm -c massachusetts-latest.osm.bz2 -S flex.lua -O flex;
```

You should not run osm2pgsql as the "postgres" user. The "postgres" user has super user rights on the database system. That user should only be used for creating databases and other things that need super user privileges. You already created the "osmuser" database user and should use that one for osm2pgsql. And then you don't have a problem with the postgres user needing access to your config/data files either.

So something like this instead:

```
osm2pgsql -d osm -U osmuser -c massachusetts-latest.osm.bz2 -S flex.lua -O flex
```

And again in step 4, you don't need the "postgres" user for this.

And btw: You don't need semicolons at the end of shell commands.

**Comment by Xetnus** [comment]
Thanks joto! I appreciate your expertise. 

I wrote those directions in the last few minutes of a hackathon and my only concern at the time was that the commands ran. I just revisited the README and implemented your suggestions in the v0.2.0-alpha branch. On Ubuntu, I had to make some changes to my pg_hba.conf file to fix an authentication issue when running the osm2pgsql command with the osmuser user specified as an argument. I added that fix to the README as well.
